### ISSUE TITLE
Blacklisting kbd may create issues with EmojiPort in the future.

### ISSUE THREAD

**Issue by PoomSmart** [hbang/StopCrashingPls#1]
https://github.com/hbang/StopCrashingPls/blob/5f1bf70cc54be64ff7a1c7b67e26655082562b90/AAAAAAstopcrashingpls.plist#L20

Just to be aware of. You don't have to do anything now because Apple has yet to release yet another set of new emojis. 😃

**Comment by kirb** [comment]
Ah, sorry! I actually downloaded all (free) tweaks that tweakCompatible was >75% confident had iOS 13 compatibility and ran through all their filter plists to find any that were specifically injecting into a daemon, so EmojiPort got missed, not being iOS 13 compatible.

I did see some crashes in kbd in my testing, so you may be up for a not-so-fun time getting EmojiPort to work on iOS 13 😕

**Comment by PoomSmart** [comment]
Ah I forgot that EmojiPort does support some versions of iOS 13. I will probably have to create something like Stop_StopCrashingPls_Pls. Hah.

**Comment by kirb** [comment]
Should I add an exception for EmojiPort.dylib? Or perhaps just remove kbd from the filter?

**Comment by PoomSmart** [comment]
@kirb The first one may be better. With that you should probably also make some kind of whitelisting system alongside your tweak.

**Comment by kirb** [comment]
Perhaps this could be adjusted to work more generically, so it loads into all processes (filter on com.apple.Foundation) and then checks whether the process looks like an “app” or “daemon”. If daemon, iterate over filter plists to check if the binary name is explicitly referenced, only load it if so. This is pretty much what I proposed Substrate should be doing.
